services:
  backend:
    build: ./backend
    container_name: stem-backend
    command: gunicorn backend_api.wsgi:application --bind 0.0.0.0:8000
    environment:
      DATABASE_URL: "postgresql://ceasor-elvis:${DB_PASSWORD}@leafy-serval-19459.j77.aws-ap-south-1.cockroachlabs.cloud:26257/stem-bootcamp-system?sslmode=verify-full"
      COCKROACH_SSL_CERT: "/app/certs/root.crt"
      CLOUDINARY_CLOUD_NAME: "${CLOUDINARY_CLOUD_NAME}"
      CLOUDINARY_API_KEY: "${CLOUDINARY_API_KEY}"
      CLOUDINARY_API_SECRET: "${CLOUDINARY_API_SECRET}"
    volumes:
      - media:/app/media
    ports:
      - "8000:8000"

  frontend-builder:
    build: ./frontend
    container_name: stem-frontend-builder
    volumes:
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - backend

  certbot:
    image: nbraun1/certbot
    container_name: certbot
    depends_on:
      - nginx
    environment:
      EMAIL: "${CERTBOT_EMAIL}"
      DOMAINS: stembootcamp.work.gd,www.stembootcamp.work.gd
      AUTHENTICATOR: webroot
      WEBROOT_PATH: /var/www/letsencrypt
      POST_HOOK_CMD: docker kill -s HUP $$(docker ps --filter "name=webserver" | awk '{print $$1}')
      CRON: "* * * * *"
    volumes:
      - ./data/certbot/letsencrypt:/etc/letsencrypt
      - ./data/certbot/www:/var/www/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - frontend_build:/usr/share/nginx/html
      - ./config:/etc/nginx/conf.d:ro
      - ./data/certbot/letsencrypt:/etc/letsencrypt:ro
      - ./data/certbot/www:/var/www/letsencrypt:ro
    depends_on:
      - backend
      - frontend-builder
      
volumes:
  media:
  frontend_build:
  certs:
